### ISSUE TITLE
Check cases with real Li-6 concentration ~5%

### ISSUE THREAD

**Issue by andrewryh** [arfc/msr-neutronics#24]
This issue could be closed when whole-core neutronic calculations with Li-6 weight fraction from 0.0005% to 5% will be finished

**Comment by andrewryh** [comment]
Ok, I'll make this curve: K-inf vs Li-6 fraction

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)

**Comment by andrewryh** [comment]
wontfix
