### ISSUE TITLE
MOSART Core Neutronics in Serpent

### ISSUE THREAD

**Issue by katyhuff** [arfc/msr-neutronics#25]
This issue can be closed when a simple full core model of the MOSART reactor has been run with Serpent on Blue Waters.

- [x] Start with serpent input file for similar reactor
- [x] Define geometry
- [x] Define materials
- [x] Run simulation

**Comment by achubbz** [comment]
Preliminary runs demonstrated that MOSART cannot be critical. Further investigation discontinued.

**Comment by katyhuff** [comment]
Thanks @achubbz
