### ISSUE TITLE
Run MSFR neutronics on BW

### ISSUE THREAD

**Issue by katyhuff** [arfc/msr-neutronics#26]
This issue can be closed when a simple full core model of the MSFR reactor has been run with Serpent on Blue Waters.

- [x] Start with serpent input file for similar reactor
- [x] Define geometry
- [x] Define materials
- [x] Run simulation

**Comment by katyhuff** [comment]
@smpark7 status?

**Comment by smpark7** [comment]
All components have been completed. Now moving on to Moltres simulations.
