### ISSUE TITLE
README for MOSART folder

### ISSUE THREAD

**Issue by katyhuff** [arfc/msr-neutronics#31]
Since the names (mosart1_1 etc) are not particularly meaningful (how do these runs differ? are they slight variations on the same input?), can you add a README to MOSART describing: 

1) the files in the MOSART folder
2) the differences between them
3) what was learned from these runs
4) any relevant references used
5) potential future areas of exploration, if someone were to pick these up again.

That is, this work doesn't need to be lost to history (it could even be an ARFC report, if you want to give it some official documentation.).

**Comment by achubbz** [comment]
@katyhuff Added README files. Additionally, all input files have comments at the top describing items 1,2,4.

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)
