### ISSUE TITLE
MSFR equilibrium fuel composition

### ISSUE THREAD

**Issue by smpark7** [arfc/msr-neutronics#48]
This issue can be closed when an MSFR equilibrium fuel composition is made available, defined by negligible change in TRU composition over a long period of time.

**Comment by andrewryh** [comment]
Will do ASAP

**Comment by smpark7** [comment]
Closed by #49

**Comment by andrewryh** [comment]
Gonna add a script which filters decay-only isotopes for Serpent.

**Comment by andrewryh** [comment]
@smpark7 I think I finished it and the issue might be closed.
